services:
  file-downloader:
    image: ghcr.io/xiaotiancai-tech/file-downloder:latest
    container_name: file-downloader
    restart: always
    networks:
      - file-downloader
    ports:
      - "8000:8000"
    volumes:
      - ./volumes:/app/data
networks:
  file-downloader:
    driver: bridge